
package com.moryaairlines.cxfsoap;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import com.cxfsoap.example.resource.BookingDetailsRequest;
import com.cxfsoap.example.resource.BookingDetailsResponse;
import com.cxfsoap.example.resource.FlightDetailsRequest;
import com.cxfsoap.example.resource.FlightDetailsResponse;
import com.cxfsoap.example.resource.ObjectFactory;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MoryaAirlines", targetNamespace = "http://resource.example.cxfsoap.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MoryaAirlines {


    /**
     * 
     * @param arg0
     * @return
     *     returns com.cxfsoap.example.resource.BookingDetailsResponse
     * @throws DocumentException
     * @throws ParseException
     * @throws IOException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getBookingDetails", targetNamespace = "http://resource.example.cxfsoap.com/", className = "com.cxfsoap.example.resource.GetBookingDetails")
    @ResponseWrapper(localName = "getBookingDetailsResponse", targetNamespace = "http://resource.example.cxfsoap.com/", className = "com.cxfsoap.example.resource.GetBookingDetailsResponse")
    public BookingDetailsResponse getBookingDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        BookingDetailsRequest arg0)
        throws DocumentException, IOException, ParseException
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns com.cxfsoap.example.resource.FlightDetailsResponse
     * @throws ParseException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFlightDetails", targetNamespace = "http://resource.example.cxfsoap.com/", className = "com.cxfsoap.example.resource.GetFlightDetails")
    @ResponseWrapper(localName = "getFlightDetailsResponse", targetNamespace = "http://resource.example.cxfsoap.com/", className = "com.cxfsoap.example.resource.GetFlightDetailsResponse")
    public FlightDetailsResponse getFlightDetails(
        @WebParam(name = "arg0", targetNamespace = "")
        FlightDetailsRequest arg0)
        throws ParseException
    ;

}
