
package com.moryaairlines.cxfsoap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MoryaAirlinesImplService", targetNamespace = "http://cxfsoap.moryaairlines.com/", wsdlLocation = "http://localhost:8081/cxfsoap/moryaflights?wsdl")
public class MoryaAirlinesImplService
    extends Service
{

    private final static URL MORYAAIRLINESIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException MORYAAIRLINESIMPLSERVICE_EXCEPTION;
    private final static QName MORYAAIRLINESIMPLSERVICE_QNAME = new QName("http://cxfsoap.moryaairlines.com/", "MoryaAirlinesImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/cxfsoap/moryaflights?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MORYAAIRLINESIMPLSERVICE_WSDL_LOCATION = url;
        MORYAAIRLINESIMPLSERVICE_EXCEPTION = e;
    }

    public MoryaAirlinesImplService() {
        super(__getWsdlLocation(), MORYAAIRLINESIMPLSERVICE_QNAME);
    }

    public MoryaAirlinesImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MORYAAIRLINESIMPLSERVICE_QNAME, features);
    }

    public MoryaAirlinesImplService(URL wsdlLocation) {
        super(wsdlLocation, MORYAAIRLINESIMPLSERVICE_QNAME);
    }

    public MoryaAirlinesImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MORYAAIRLINESIMPLSERVICE_QNAME, features);
    }

    public MoryaAirlinesImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MoryaAirlinesImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MoryaAirlines
     */
    @WebEndpoint(name = "MoryaAirlinesImplPort")
    public MoryaAirlines getMoryaAirlinesImplPort() {
        return super.getPort(new QName("http://cxfsoap.moryaairlines.com/", "MoryaAirlinesImplPort"), MoryaAirlines.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MoryaAirlines
     */
    @WebEndpoint(name = "MoryaAirlinesImplPort")
    public MoryaAirlines getMoryaAirlinesImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cxfsoap.moryaairlines.com/", "MoryaAirlinesImplPort"), MoryaAirlines.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MORYAAIRLINESIMPLSERVICE_EXCEPTION!= null) {
            throw MORYAAIRLINESIMPLSERVICE_EXCEPTION;
        }
        return MORYAAIRLINESIMPLSERVICE_WSDL_LOCATION;
    }

}
